project:
  type: website
  resources: 
    - assets/

website:
  title: "gnczi theorycrafts"
  favicon: /assets/foxi.jpeg
  navbar:
    logo: /assets/foxi2.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    left: "© 2026 gnczi theorycrafts"

format:
  html:
    image: /assets/foxi.jpeg
    code-fold: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    layout:
      xaxis:
        font:
          weight: bold
